#pragma once

// --- Dinh nghia Pin (Quan trong) ---
#define PIN_SONAR_TRIG ...
#define PIN_SONAR_ECHO ...
#define PIN_TEMP_SENSOR ... // Vi du: D4 (neu la DHT22)
#define PIN_RFID_SDA ...
#define PIN_RFID_RST ...
#define PIN_PHOTORESISTOR A0
#define PIN_SERVO ...
#define PIN_FAN ...
#define PIN_LIGHT ...
#define PIN_NIGHT_LIGHT ...
#define PIN_BUZZER ...
#define PIN_OLED_SDA ...
#define PIN_OLED_SCL ...

// --- Cau hinh WiFi & MQTT ---
#define MQTT_BROKER "DIA_CHI_IP_CUA_BROKER"
#define MQTT_PORT 1883
#define MQTT_CLIENT_ID "ESP8266_1"

// --- Dinh nghia MQTT Topics ---
// Topics ma ESP1 se PUBLISH
#define TOPIC_PUB_TEMPERATURE "smartroom/temperature"
#define TOPIC_PUB_DOOR_STATE "smartroom/door/state"

// Topics ma ESP1 se SUBSCRIBE
#define TOPIC_SUB_FAN_CONTROL "smartroom/control/fan"       // Nhan "ON" hoac "OFF"
#define TOPIC_SUB_LIGHT_CONTROL "smartroom/control/light"   // Nhan "ON" hoac "OFF"
#define TOPIC_SUB_TEMP_THRESHOLD "smartroom/config/temp_threshold"
#define TOPIC_SUB_ALARM_TIME "smartroom/config/alarm_time"